# Copyright 2020 TataElxsi
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
---
options:
    diameter_port:
        type: int
        description: 'diameter_port is used for
                      communication between icscf and hss'
        default: 3869
