#!/bin/bash
# Copyright 2020 Tata Elxsi
#
# Licensed under the Apache License, Version 2.0 (the License); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# For those usages not covered by the Apache License, Version 2.0 please
# contact: canonical@tataelxsi.onmicrosoft.com
#
# To get in touch with the maintainers, please contact:
# canonical@tataelxsi.onmicrosoft.com
##


USER=`action-get user`
DOMAIN=`action-get domain`

mysql -D hss_db -u root -proot -se "delete from impi where identity='$USER@$DOMAIN'"


id_impu=$(mysql -D hss_db -u root -proot -se "select id from impu where identity='sip:$USER@$DOMAIN'")

mysql -D hss_db -u root -proot -se "delete from impi_impu where id_impu=$id_impu"

mysql -D hss_db -u root -proot -e "delete from impu_visited_network where id_impu=$id_impu"

mysql -D hss_db -u root -proot -se "delete from impu where identity='sip:$USER@$DOMAIN'"

mysql -D hss_db -u root -proot -se "delete from imsu where name='$USER'"
