# Copyright 2020 TataElxsi
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
---
options:
  sql_port:
    type: int
    description: 'sql_port is used for exposing db application'
    default: 3306
