# Copyright 2020 TataElxsi
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
    diaport:
        type: int
        description: 'diameterport'
        default: 3868
    hssport:
        type: int
        description: 'hss port'
        default: 8080
